config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: %i[index show] do
    resources :reviews, only: %i[create destroy]
  end
  resources :sections, only: [:show]
  resource :carts, only: [:show] do
    put :add_item
    delete :remove_item
  end
  resources :orders, only: %i[create show]

  namespace :admin do
    root to: 'dashboard#index'
    resources :products, :sections, :users, except: %i[edit update show]
    resources :orders, only: %i[index destroy]
  end


  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/shutdown' => 'users#destroy'
  get '/getintouch' => 'contact#new'
  post 'submit_contact' => 'contact#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'legal' => 'legal#index'

  #HTTP error routes
  get '/403' => 'errors#forbidden'
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unacceptable'
  get '/500' => 'errors#internal_error'

end

app/models/user.rb
# Represents a user account - Uses Bcrypt to authenticate
#                           - 1 user can leave many reviews, which will get removed when the user closes their account
#                           - 1 user can place many orders, which will get deleted when the account is closed
#                           - Only one account per email address allowed.
#                           - A user must provide their name and email address to have an account
class User < ApplicationRecord
  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates_presence_of :firstName, :lastName, :email
  validates :email, uniqueness: true
end

app/controllers/admin/users_controller.rb
# Admin manager controller - inherits admin check from auth controller
class Admin::UsersController < Admin::AuthorisedController
  # Display a table of all users and key attribs, sorted by ID
  def index
    @users = User.order(id: :desc).all
  end

  # Create and store new user from given strong params
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "New user created"
      redirect_to admin_users_path
    else
      render :'admin/users/new'
    end
  end

  # Use form to gather necessary info to create a new user
  def new
    @user = User.new
  end

  # Delete a target user and all orders they've placed along with all reviews made
  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end

  private
  # A user can only take: first+last names, email, password+confirmation and if they are an admin or not as params
  # These strong params differ from the standard user controller strong params in that they allow for making users admin
  # Having a signup form that allows to make yourself an admin doesn't seem smart
  def user_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
# User account Controller - manage opening and closing of user accounts.
class UsersController < ApplicationController
  before_action :chck_session, only: [:create, :new]

  # Use a form to collect new user info. Can't already be logged in when trying to signup
  def new
    @user=User.new
  end

  # Create a new user from the strong params and save
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = t(:acc_created)
      redirect_to root_url
    else
      flash[:danger] = t(:something_wrong)
      redirect_to root_url
    end
  end

  # Close the currently logged in account - taking with it all placed orders and reviews written - right to be forgotten
  def destroy
    if curr_user.nil?
      flash[:warning] = t(:not_logged_in)
    else
      curr_user.destroy
      session[:user_id] = nil
      flash[:warning] = t(:acc_closed)
    end
    redirect_to root_url
  end

  private
  # When making a user only name, email and password + conf are acceptable params
  def user_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<!--Signup form, validated with JS -->
<%= form_for @user, url: signup_url, :html => {:id => 'SignupForm'} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:" %>
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :firstName, t('.fname_prompt') %>
  <%= f.text_field :firstName,:html => {:id => 'Fname'}  %>
  <%= f.label :lasstName, t('.lname_prompt') %>
  <%= f.text_field :lastName, :html => {:id => 'Lname'}  %>
  <br>
  <%= f.label :email, t('.email_prompt') %>
  <%= f.text_field :email, :html => {:id => 'Email'} %>
  <br>
  <%= f.label :password, t('.pword_prompt') %>
  <%= f.password_field :password, :html => {:id => 'Password'} %>
  <%= f.label :password, t('.pword_prompt') %>
  <%= f.password_field :password_confirmation, :html => {:id => 'PasswordConf'} %>
  <br>
  <%= f.submit "Submit"%>
<% end %>

app/views/users/new.html.erb
<!--Signup page -->
<h1 class="pageTitle"><%=t('.page_title') %></h1>
<%= render 'form'%>