config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: %i[index show] do
    resources :reviews, only: %i[create destroy]
  end
  resources :sections, only: [:show]
  resource :carts, only: [:show] do
    put :add_item
    delete :remove_item
  end
  resources :orders, only: %i[create show]

  namespace :admin do
    root to: 'dashboard#index'
    resources :products, :sections, :users, except: %i[edit update show]
    resources :orders, only: %i[index destroy]
  end


  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/shutdown' => 'users#destroy'
  get '/getintouch' => 'contact#new'
  post 'submit_contact' => 'contact#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'legal' => 'legal#index'

  #HTTP error routes
  get '/403' => 'errors#forbidden'
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unacceptable'
  get '/500' => 'errors#internal_error'

end

app/controllers/carts_controller.rb
# Shopping cart controller - track items and manage quantities. Must be logged in to interact with
class CartsController < ApplicationController
  before_action :req_login
  # Add target product id to the cart after checking it is a real product
  def add_item
    prod_id = params[:product_id].to_s
    unless Product.find(prod_id).nil?
      item = cart[prod_id] || {"Num" => 0}
      item["Num"] += 1
      cart[prod_id] = item
      update_cart cart
      flash[:success] = t('itm_added')
      redirect_back fallback_location: :root
    end
  end

  # Remove target product id from cart
  def remove_item
    prod_id = params[:product_id].to_s
    item = cart[prod_id] || {"Num" => 0}
    item["Num"] -=1
    cart[prod_id] = item
    cart.delete(prod_id) if item["Num"] < 1
    update_cart cart
    flash[:success] = t('itm_removed')
    redirect_back fallback_location: :root
  end
end

app/views/carts/_entry.html.erb
<!--Collate various stuff about a given item in cart. Have + and - to modify number in cart -->
<%num = info["Num"].to_i %>
<%if product = Product.find_by(id: prodId) %>
  <%itemTotal = product.price * num %>
  <%@totalCost += itemTotal %>
  <tr>
    <td>
      <%= image_tag product.image.small.url %>
    </td>
    <td>
      <h5><%=product.name %></h5><br>
      <p><%=product.description %></p>
    </td>
    <td>
      <%= humanized_money_with_symbol product.price %>
    </td>
    <td>
      <%= num %>
      <%= link_to remove_item_carts_path(product_id: prodId), method: :delete do %> - <%end %>
      <%= link_to add_item_carts_path(product_id: prodId), method: :put do %> + <%end %>
    </td>
    <td>
      <%= humanized_money_with_symbol itemTotal%>
    </td>
  </tr>
<%end %>

app/views/carts/show.html.erb
<!--Build a table of all items in the shopping cart. Or display a message if empty -->
<h1 class="pageTitle"><%=t('.page_title') %></h1>
<%if cart.blank? %>
  <h1 class="alert"><%=t('.empty') %></h1>
<%else%>
  <table>
    <thead>
      <tr>
        <th><%=t('.item_title') %></th>
        <th></th>
        <th><%=t('.cost_title') %></th>
        <th><%=t('.quan_title') %></th>
        <th><%=t('.price_title') %></th>
      </tr>
    </thead>
    <tbody>
      <%@totalCost = 0 %>
      <%cart.each do |prodId, info| %>
        <%= render 'entry', prodId: prodId, info: info%>
      <%end %>
    </tbody>
    <tfoot>
      <tr>
        <th>
          <%=t('.total_title') %>
        </th>
        <th>
          <%= humanized_money_with_symbol @totalCost%>
        </th>
      </tr>
    </tfoot>
  </table>
  <%=form_for :order, url: orders_url do |f|%>
    <%= f.email_field :Email, value: curr_user.email%>
    <%= f.submit t('.sub_button')%>
  <%end %>
<%end%>