config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: %i[index show] do
    resources :reviews, only: %i[create destroy]
  end
  resources :sections, only: [:show]
  resource :carts, only: [:show] do
    put :add_item
    delete :remove_item
  end
  resources :orders, only: %i[create show]

  namespace :admin do
    root to: 'dashboard#index'
    resources :products, :sections, :users, except: %i[edit update show]
    resources :orders, only: %i[index destroy]
  end


  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/shutdown' => 'users#destroy'
  get '/getintouch' => 'contact#new'
  post 'submit_contact' => 'contact#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'legal' => 'legal#index'

  #HTTP error routes
  get '/403' => 'errors#forbidden'
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unacceptable'
  get '/500' => 'errors#internal_error'

end

app/controllers/contact_controller.rb
# Contact form controller
class ContactController < ApplicationController
  # Location of form
  def new
  end

  def create
    #Form Submitted time to do mailer jazz
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    if email.blank?
      flash[:alert] = t(:email_request_flash)
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = t(:in_touch)
    end
    redirect_to root_path
  end
end

app/views/contact/_form.html.erb
<!--Collect all info required to send an email to store manager. Validated in JS -->
<%= form_tag submit_contact_path,:id => 'ContactForm', method: 'post' do %>
  <%=  label_tag :name, t('.name')%>
    <%= text_field_tag :name, '',title: t('.enter_name')%>
  <br>
  <%= label_tag :email, t('.email')%>
    <%= email_field_tag :email, '',title: t('.enter_email')%>
  <br>
  <%= label_tag :telephone, t('.telephone')%>
    <%= telephone_field_tag :telephone,'' ,title: t('.enter_telephone')%>
  <br>
  <%= label_tag :message, t('.message')%>
    <%= text_field_tag :message, '', title: t('.enter_message')%>
  <%= submit_tag t('.sub_button')%>
<%end %>

app/views/contact/new.html.erb
<h1 class="pageTitle"><%=t('.page_title') %></h1>
<%= render 'form'%>