config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: %i[index show] do
    resources :reviews, only: %i[create destroy]
  end
  resources :sections, only: [:show]
  resource :carts, only: [:show] do
    put :add_item
    delete :remove_item
  end
  resources :orders, only: %i[create show]

  namespace :admin do
    root to: 'dashboard#index'
    resources :products, :sections, :users, except: %i[edit update show]
    resources :orders, only: %i[index destroy]
  end


  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/shutdown' => 'users#destroy'
  get '/getintouch' => 'contact#new'
  post 'submit_contact' => 'contact#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'legal' => 'legal#index'

  #HTTP error routes
  get '/403' => 'errors#forbidden'
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unacceptable'
  get '/500' => 'errors#internal_error'

end

app/models/product.rb
# Represents a prdouct that is listed in the store - Many products belong to 1 section
#                                                  - A product can only be a part of 1 section
#                                                  - 1 product has Many reviews, these reviews can't exist without the
#                                                    product
#                                                  - Price is stored in pence then gem takes care of converting to local
#                                                    currency and displaying with correct symbol
#                                                  - Must have name,desc,price,stock count and link to a prod section
class Product < ApplicationRecord
  belongs_to :section
  has_many :reviews, -> {order(created_at: :desc)}, dependent: :destroy
  monetize :pricePence, as: "price", numericality: true
  mount_uploader :image, ProductImgUploader
  validates_presence_of :name, :price, :stockCount, :section_id, :description, :image
end

app/controllers/admin/products_controller.rb
# Product manager controller - inherits admin check from auth controller
class Admin::ProductsController < Admin::AuthorisedController
  # Display a table of all products sorted by ID
  def index
    @products = Product.order(id: :desc).all
  end

  # From given strong params create and store new product
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "New product created"
      redirect_to admin_products_path
    else
      render :'admin/products/new'
    end
  end

  # Use form to gather required info for new product
  def new
    @product = Product.new
  end

  # Delete a target product
  def destroy
    @product = Product.find params[:id]
    @product.destroy
    flash[:success] = "Product deleted"
    redirect_to admin_products_path
  end

  private
  # A product can only take name, description, stock count, price, image and section as parameters
  def product_params
    params.require(:product).permit(:name, :description, :stockCount, :pricePence, :image, :section_id)
  end
end

app/controllers/products_controller.rb
# Product controller - manage the home page table and per product views
class ProductsController < ApplicationController
  # Display the table of products by date added
  def index
    @products = Product.all.order(created_at: :desc)
    render stream: true
  end

  # Display a specific product given an ID
  def show
    @product = Product.find params[:id]
  end
end

app/views/products/_product.html.erb
<!--Partial to show key product info and have cart shaped button to add to cart -->
<article class="product">
  <header>
    <%=link_to product do %>
      <%= image_tag product.image.thumb.url, alt: product.name %>
      <h3><%= product.name %></h3>
    <%end%>
  </header>
  <p>
    <%= product.description %>
  </p>
  <footer>
    <% if product.stockCount >0 %>
      <%= link_to add_item_carts_path(product_id: product.id), method: :put do %>
        <%= fa_icon "shopping-cart", text: t('.add_cart') %>
        <%end%>
    <%end%>
    <%= humanized_money_with_symbol product.price %>
  </footer>
</article>

app/views/products/index.html.erb
<!--Display a grid of all products on sale. This is the home page of the site -->
<h1 class="pageTitle"><%= t('.page_title')%></h1>
<div class="productTable">
  <%= render @products%>
</div>

app/views/products/show.html.erb
<!--Display a specific product th reviews and allow for a review to be left -->
<section class="prdouctFocus">
  <h2><%= link_to @product.section.name, @product.section %> - <%= @product.name %></h2>
  <article class="productDetails">
    <div class="row row-no-gutters">
      <div class="col-sm-5 col-lg-4">
        <%=image_tag @product.image.main.url %>
      </div>
      <div class="col-lg-8 col-sm-9 col-xs-8">
        <dl class="dl-horizontal">
          <dt>Product Name:</dt>
          <dd><%= @product.name %></dd>
          <dt><%=t('.desc_title') %></dt>
          <dd><%= @product.description %></dd>
          <dt><%=t('.stock_title') %></dt>
          <dd><%= @product.stockCount %></dd>
          <dt><%=t('.price_title') %></dt>
          <dd><%= humanized_money_with_symbol @product.price %></dd>
          <dd>
            <% if @product.stockCount >0 %>
              <%= link_to add_item_carts_path(product_id: @product.id), method: :put do %>
                <%= fa_icon "shopping-cart", text: t('.add_cart') %>
              <%end%>
            <%end%>
          </dd>
        </dl>
      </div>
      <div class="col-lg-8 col-sm-9 col-xs-8">
      <h3><%=t('.reviews_title') %></h3><br>
      <%if curr_user %>
        <%= form_for(Review.new, url: product_reviews_url(@product,@review)) do |f|%>
          <%= f.select :rating,
                       options_for_select([[t('.lvl5'),5],
                                           [t('.lvl4'), 4],
                                           [t('.lvl3'), 3],
                                           [t('.lvl2'), 2],
                                           [t('.lvl1'), 1],
                                           [t('.lvl0'),0]
                                          ])%><br>
          <%= f.text_area :content%><br>
          <%= f.submit t('.sub_button') %>
        <%end %>
      <%end %>
      <% @product.reviews.each do |i| %>
        <strong><%= i.rating%> / 5</strong> - <%=i.content %> <br>
        <% if i.user == curr_user %>
          <%= link_to t('.remove_button'), product_review_path(@product, i), :method => :delete%>
        <%end %>
        <hr>
      <% end %>
      </div>
    </div>
  </article>
</section>